name: srt-dev
channels:
  - conda-forge
dependencies:
  - astroplan
  - astropy
  - fastapi
  - numpy
  - pandas
  - parse
  - pip
  - pydantic
  - pydantic-core
  - pyjwt
  - pyserial
  - python=3.10
  - python-dotenv
  - pyvisa
  - pyzmq
  - scipy
  - starlette
  - uvicorn
  - uvloop
  - pip:
      - -e .

