STATION:
  latitude: 34.140
  longitude: -118.124
  name: Caltech
EMERGENCY_CONTACT:
  name: Michael Gutierrez
  email: magutier@caltech.edu
  phone_number: 941-330-4460
AZLIMITS:
  lower_bound: -89.0
  upper_bound: 449.0
ELLIMITS:
  lower_bound: 15.0
  upper_bound: 81.0
STOW_LOCATION:
  azimuth: 179
  elevation: 81
CAL_LOCATION:
  azimuth: 270.0
  elevation: 16.0
HORIZON_POINTS:
  - azimuth: 0
    elevation: 0
  - azimuth: 120
    elevation: 5
  - azimuth: 240
    elevation: 5
  - azimuth: 360
    elevation: 0
MOTOR_TYPE: CALTECH6M
MOTOR_PORT: COM1
MOTOR_BAUDRATE: 115200
RADIO_CF: 1420000000
RADIO_SF: 2400000
RADIO_FREQ_CORR: -50000
RADIO_NUM_BINS: 256
RADIO_INTEG_CYCLES: 100000
RADIO_AUTOSTART: Yes
NUM_BEAMSWITCHES: 25
BEAMWIDTH: 7.0
TSYS: 171
TCAL: 290
SAVE_DIRECTORY: ~/SRT-Saves
RUN_HEADLESS: No
DASHBOARD_PORT: 8080
DASHBOARD_HOST: 0.0.0.0
DASHBOARD_DOWNLOADS: Yes
DASHBOARD_REFRESH_MS: 500
