"""
Generates TypeScript interfaces from the Pydantic models in
backend/app/models/. This is the ONLY place TS types for shared
data shapes should come from — never hand-write a matching
interface in the frontend.

Pipeline:
  Pydantic BaseModel
    -> .model_json_schema()       (Pydantic's built-in JSON Schema export)
    -> write combined schema.json
    -> shell out to `json-schema-to-typescript` (npm package, already
       a devDependency in frontend/) to emit the .d.ts file

Run via: conda run -n srt-dev python scripts/generate_ts_types.py
Wired into the frontend build/dev lifecycle by vite.config.ts (see
frontend/vite.config.ts) so this never has to be remembered manually.
"""

import json
import subprocess
import sys
from pathlib import Path

# Make daemon/ importable regardless of cwd
SRT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SRT_ROOT / "daemon"))

from telescope_types import ( # pyright: ignore[reportMissingImports]
    LprParams,
    RotorState,
    SpectrumConfig,
    SpectrumFrame,
    DaemonStatus,
    DaemonConfig,
)

OUTPUT_DIR = SRT_ROOT / "svelte-frontend" / "src" / "lib" / "generated"
SCHEMA_TMP_DIR = SRT_ROOT / ".schema-tmp"

# Every model that crosses the Python<->TS boundary goes here.
MODELS = [LprParams, RotorState, SpectrumConfig, SpectrumFrame, DaemonStatus, DaemonConfig]


def build_combined_schema() -> dict:
    """
    Combine all models into one JSON Schema document with each model
    as a named definition, so json-schema-to-typescript emits one
    .d.ts file with all interfaces instead of N separate files.
    """
    definitions = {}
    for model in MODELS:
        schema = model.model_json_schema(
            ref_template="#/definitions/{model}"
        )
        # Pydantic nests sub-model defs under "$defs" — merge those in too
        sub_defs = schema.pop("$defs", {})
        definitions.update(sub_defs)
        definitions[model.__name__] = schema
 
    return {
        "title": "GeneratedTypes",
        "definitions": definitions,
        # json-schema-to-typescript needs each definition referenced
        # from somewhere to emit it; this dummy root does that.
        #
        # BUG FIX: this must only reference the models actually listed
        # in MODELS, not every key in `definitions` — `definitions`
        # also contains every nested sub-model pulled in transitively
        # via $defs (DriverState, AmpCurrent, LprParams, Location, ...).
        # Referencing those from the root TOO (in addition to their
        # existing reference from inside e.g. RotorState.fsm_state)
        # made json-schema-to-typescript treat them as needing two
        # separate exports, emitting both `DriverState` and a second,
        # identical `DriverState1`. Nested types are already reachable
        # for codegen purposes via the definitions they're already
        # referenced from — they don't need their own root entry.
        "type": "object",
        "properties": {
            model.__name__: {"$ref": f"#/definitions/{model.__name__}"}
            for model in MODELS
        },
    }


def main():
    SCHEMA_TMP_DIR.mkdir(exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    schema = build_combined_schema()
    schema_path = SCHEMA_TMP_DIR / "combined_schema.json"
    schema_path.write_text(json.dumps(schema, indent=2))

    output_path = OUTPUT_DIR / "types.ts"

    result = subprocess.run(
        [
            "pnpx",
            "json-schema-to-typescript",
            str(schema_path),
            "--bannerComment",
            (
                "/* eslint-disable */\n"
                "/**\n"
                " * AUTO-GENERATED by scripts/generate_ts_types.py\n"
                " * Source of truth: backend/app/models/telescope.py\n"
                " * Do not edit this file directly — run the generator instead.\n"
                " */"
            ),
            "--no-additionalProperties",
        ],
        capture_output=True,
        text=True,
        cwd=SRT_ROOT / "svelte-frontend",
    )

    if result.returncode != 0:
        print("Type generation failed:", file=sys.stderr)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)

    output_path.write_text(result.stdout)
    print(f"Generated {output_path.relative_to(SRT_ROOT)}")


if __name__ == "__main__":
    main()
